import {
  ENCODER_OPTION_APPLICABILITY,
  getToolOptionsSchema,
} from "@image-everything/contracts"

import type {
  SerializableValue,
  ToolCategory,
  ToolDefinition,
  ToolManifest,
} from "./types"

const formatOptions = [
  { label: "JPEG", value: "jpeg" },
  { label: "PNG", value: "png" },
  { label: "WebP", value: "webp" },
  { label: "AVIF", value: "avif" },
  { label: "GIF", value: "gif" },
  { label: "TIFF", value: "tiff" },
] as const

const fitOptions = [
  { label: "Cover", value: "cover" },
  { label: "Contain", value: "contain" },
  { label: "Fill", value: "fill" },
  { label: "Inside", value: "inside" },
  { label: "Outside", value: "outside" },
] as const

const positionOptions = [
  { label: "Center", value: "center" },
  { label: "Top", value: "top" },
  { label: "Top right", value: "right top" },
  { label: "Right", value: "right" },
  { label: "Bottom right", value: "right bottom" },
  { label: "Bottom", value: "bottom" },
  { label: "Bottom left", value: "left bottom" },
  { label: "Left", value: "left" },
  { label: "Top left", value: "left top" },
  { label: "Entropy focal point", value: "entropy" },
  { label: "Attention focal point", value: "attention" },
] as const

const anchorOptions = [
  { label: "Top left", value: "top-left" },
  { label: "Top", value: "top" },
  { label: "Top right", value: "top-right" },
  { label: "Left", value: "left" },
  { label: "Center", value: "center" },
  { label: "Right", value: "right" },
  { label: "Bottom left", value: "bottom-left" },
  { label: "Bottom", value: "bottom" },
  { label: "Bottom right", value: "bottom-right" },
] as const

const metadataDisposition = {
  type: "select",
  path: "metadata",
  label: "Metadata policy",
  options: [
    { label: "Strip metadata", value: "strip" },
    { label: "Preserve metadata", value: "preserve" },
    { label: "Privacy-safe metadata", value: "privacy" },
  ],
} as const

const quality = {
  type: "range",
  path: "quality",
  label: "Quality",
  description: "Encoder quality from 1 (smallest) to 100 (highest fidelity).",
  min: 1,
  max: 100,
  step: 1,
  unit: "%",
} as const

const outputFormat = {
  type: "select",
  path: "format",
  label: "Output format",
  options: formatOptions,
} as const

export function formatsForEncoderOption(option: string): string[] {
  return Object.entries(ENCODER_OPTION_APPLICABILITY)
    .filter(([, options]) => options.includes(option))
    .map(([format]) => format)
}

export const CATEGORY_META: Record<
  ToolCategory,
  { label: string; description: string }
> = {
  optimize: {
    label: "Optimize & export",
    description:
      "Compress, resize, convert, and generate delivery-ready assets.",
  },
  geometry: {
    label: "Geometry & canvas",
    description: "Crop, rotate, trim, extend, and manage transparency.",
  },
  color: {
    label: "Color & effects",
    description: "Tune color, tone, focus, filters, and pixel effects.",
  },
  composition: {
    label: "Composition",
    description: "Watermark, frame, and arrange multiple images.",
  },
  metadata: {
    label: "Metadata & analysis",
    description: "Inspect, clean, edit, measure, and compare images.",
  },
  automation: {
    label: "Automation",
    description: "Build reusable pipelines and process whole batches.",
  },
}

export const TOOL_MANIFEST = [
  {
    id: "compress",
    slug: "compress",
    title: "Compress image",
    shortTitle: "Compress",
    description:
      "Reduce file size with contextual controls for JPEG, PNG, WebP, AVIF, GIF, and TIFF.",
    category: "optimize",
    endpoint: "/api/v2/images/compress",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      format: "jpeg",
      quality: 80,
      lossless: false,
      progressive: true,
      mozjpeg: true,
      effort: 4,
      compressionLevel: 9,
      chromaSubsampling: "4:2:0",
      background: "#ffffff",
      metadata: "strip",
    },
    controls: [
      outputFormat,
      {
        ...quality,
        visibleWhen: {
          path: "format",
          oneOf: formatsForEncoderOption("quality"),
        },
      },
      {
        type: "boolean",
        path: "lossless",
        label: "Lossless",
        description:
          "Use a lossless encoder when the selected codec supports it.",
        visibleWhen: {
          path: "format",
          oneOf: formatsForEncoderOption("lossless"),
        },
      },
      {
        type: "boolean",
        path: "progressive",
        label: "Progressive JPEG",
        visibleWhen: { path: "format", equals: "jpeg" },
      },
      {
        type: "boolean",
        path: "mozjpeg",
        label: "MozJPEG",
        visibleWhen: { path: "format", equals: "jpeg" },
      },
      {
        type: "select",
        path: "chromaSubsampling",
        label: "Chroma subsampling",
        visibleWhen: { path: "format", equals: "jpeg" },
        options: [
          { label: "4:2:0 (smaller)", value: "4:2:0" },
          { label: "4:4:4 (sharper color)", value: "4:4:4" },
        ],
      },
      {
        type: "range",
        path: "effort",
        label: "Encoder effort",
        min: 0,
        max: 9,
        step: 1,
        visibleWhen: {
          path: "format",
          oneOf: formatsForEncoderOption("effort"),
        },
      },
      {
        type: "range",
        path: "compressionLevel",
        label: "PNG compression level",
        min: 0,
        max: 9,
        step: 1,
        visibleWhen: { path: "format", equals: "png" },
      },
      {
        type: "color",
        path: "background",
        label: "Flattening background",
        visibleWhen: { path: "format", equals: "jpeg" },
      },
      metadataDisposition,
    ],
    keywords: ["optimize", "quality", "small", "jpeg", "png", "webp", "avif"],
  },
  {
    id: "compress-to-size",
    slug: "compress-to-size",
    title: "Compress to a target size",
    shortTitle: "Compress to size",
    description:
      "Search a bounded quality range to produce the closest file at or below your byte target.",
    category: "optimize",
    endpoint: "/api/v2/images/compress-to-size",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      format: "jpeg",
      targetBytes: 500000,
      minQuality: 20,
      maxQuality: 92,
    },
    controls: [
      {
        type: "select",
        path: "format",
        label: "Output format",
        options: formatOptions.filter((option) =>
          ["jpeg", "webp", "avif"].includes(option.value)
        ),
      },
      {
        type: "number",
        path: "targetBytes",
        label: "Target size",
        description: "Maximum desired output size in bytes.",
        min: 1024,
        max: 26214400,
        step: 1024,
        unit: "bytes",
      },
      {
        type: "range",
        path: "minQuality",
        label: "Minimum quality",
        min: 1,
        max: 100,
      },
      {
        type: "range",
        path: "maxQuality",
        label: "Maximum quality",
        min: 1,
        max: 100,
      },
      {
        type: "range",
        path: "tolerancePercent",
        label: "Size tolerance",
        min: 0,
        max: 25,
        step: 1,
        unit: "%",
      },
      {
        type: "number",
        path: "maxIterations",
        label: "Search iterations",
        min: 1,
        max: 12,
        step: 1,
      },
      {
        type: "color",
        path: "background",
        label: "Flattening background",
        visibleWhen: { path: "format", equals: "jpeg" },
      },
      metadataDisposition,
    ],
    keywords: ["target", "bytes", "email", "upload limit", "quality search"],
  },
  {
    id: "resize",
    slug: "resize",
    title: "Resize image",
    shortTitle: "Resize",
    description:
      "Resize by exact dimensions or percentage with fit, position, kernel, background, and enlargement controls.",
    category: "optimize",
    endpoint: "/api/v2/images/resize",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      width: 1600,
      fit: "inside",
      position: "center",
      kernel: "lanczos3",
      background: "#00000000",
      withoutEnlargement: true,
      withoutReduction: false,
    },
    controls: [
      {
        type: "number",
        path: "width",
        label: "Width",
        min: 1,
        max: 20000,
        unit: "px",
        optional: true,
      },
      {
        type: "number",
        path: "height",
        label: "Height",
        min: 1,
        max: 20000,
        unit: "px",
        optional: true,
      },
      {
        type: "number",
        path: "percent",
        label: "Percentage",
        min: 1,
        max: 1000,
        unit: "%",
        optional: true,
      },
      { type: "select", path: "fit", label: "Fit", options: fitOptions },
      {
        type: "select",
        path: "position",
        label: "Position",
        options: positionOptions,
      },
      {
        type: "select",
        path: "kernel",
        label: "Sampling kernel",
        options: [
          { label: "Nearest", value: "nearest" },
          { label: "Cubic", value: "cubic" },
          { label: "Mitchell", value: "mitchell" },
          { label: "Lanczos 2", value: "lanczos2" },
          { label: "Lanczos 3", value: "lanczos3" },
        ],
      },
      {
        type: "color",
        path: "background",
        label: "Background",
        optional: true,
      },
      {
        type: "boolean",
        path: "withoutEnlargement",
        label: "Do not enlarge smaller images",
      },
      {
        type: "boolean",
        path: "withoutReduction",
        label: "Do not reduce larger images",
      },
    ],
    keywords: ["dimensions", "width", "height", "percentage", "thumbnail"],
  },
  {
    id: "convert",
    slug: "convert",
    title: "Convert image format",
    shortTitle: "Convert",
    description:
      "Encode to an explicit still-image format with no silent fallback to JPEG.",
    category: "optimize",
    endpoint: "/api/v2/images/convert",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      format: "png",
      quality: 85,
      lossless: false,
      progressive: false,
      effort: 4,
      compressionLevel: 9,
      background: "#ffffff",
      metadata: "strip",
    },
    controls: [
      outputFormat,
      {
        ...quality,
        visibleWhen: {
          path: "format",
          oneOf: formatsForEncoderOption("quality"),
        },
      },
      {
        type: "boolean",
        path: "lossless",
        label: "Lossless",
        visibleWhen: {
          path: "format",
          oneOf: formatsForEncoderOption("lossless"),
        },
      },
      {
        type: "boolean",
        path: "progressive",
        label: "Progressive JPEG",
        visibleWhen: { path: "format", equals: "jpeg" },
      },
      {
        type: "range",
        path: "effort",
        label: "Encoder effort",
        min: 0,
        max: 9,
        step: 1,
        visibleWhen: {
          path: "format",
          oneOf: formatsForEncoderOption("effort"),
        },
      },
      {
        type: "range",
        path: "compressionLevel",
        label: "PNG compression level",
        min: 0,
        max: 9,
        step: 1,
        visibleWhen: { path: "format", equals: "png" },
      },
      {
        type: "color",
        path: "background",
        label: "Flattening background",
        optional: true,
        visibleWhen: { path: "format", equals: "jpeg" },
      },
      metadataDisposition,
    ],
    notes: [
      "HEIC and HEIF inputs require an explicit encodable output format.",
    ],
    keywords: ["webp to png", "jpeg", "avif", "gif", "tiff", "format"],
  },
  {
    id: "responsive",
    slug: "responsive-set",
    title: "Generate a responsive image set",
    shortTitle: "Responsive set",
    description:
      "Create several widths and formats in one request, returned as a ZIP with a machine-readable manifest.",
    category: "optimize",
    endpoint: "/api/v2/images/responsive",
    inputKind: "single",
    resultKind: "zip",
    controlMode: "fields",
    defaults: {
      widths: [320, 640, 960, 1280],
      formats: ["webp", "jpeg"],
      quality: 82,
      fit: "inside",
      withoutEnlargement: true,
      background: "#ffffff",
      filenamePrefix: "image",
    },
    controls: [
      {
        type: "number-list",
        path: "widths",
        label: "Widths",
        description: "Comma-separated output widths.",
        minItems: 1,
        maxItems: 12,
      },
      {
        type: "choice-list",
        path: "formats",
        label: "Formats",
        options: formatOptions,
        minItems: 1,
        maxItems: 6,
      },
      {
        ...quality,
        description:
          "Applied to responsive variants whose encoders use a quality setting.",
      },
      { type: "select", path: "fit", label: "Fit", options: fitOptions },
      {
        type: "boolean",
        path: "withoutEnlargement",
        label: "Do not enlarge smaller images",
      },
      { type: "color", path: "background", label: "Background" },
      {
        type: "text",
        path: "filenamePrefix",
        label: "Filename prefix",
        maxLength: 80,
      },
    ],
    keywords: ["srcset", "responsive", "web", "zip", "variants"],
  },
  {
    id: "quick-enhance",
    slug: "quick-enhance",
    title: "Quick enhance",
    shortTitle: "Quick enhance",
    description:
      "Apply deterministic auto-orientation, tonal normalization, color modulation, and sharpening.",
    category: "optimize",
    endpoint: "/api/v2/images/quick-enhance",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      normalize: true,
      brightness: 1,
      saturation: 1,
      hue: 0,
      sharpen: true,
    },
    controls: [
      { type: "boolean", path: "normalize", label: "Normalize contrast" },
      {
        type: "range",
        path: "brightness",
        label: "Brightness",
        min: 0.1,
        max: 3,
        step: 0.05,
      },
      {
        type: "range",
        path: "saturation",
        label: "Saturation",
        min: 0,
        max: 3,
        step: 0.05,
      },
      {
        type: "range",
        path: "hue",
        label: "Hue",
        min: -360,
        max: 360,
        step: 1,
        unit: "°",
      },
      { type: "boolean", path: "sharpen", label: "Sharpen" },
    ],
    keywords: ["enhance", "normalize", "brightness", "saturation", "sharpen"],
  },
  {
    id: "crop",
    slug: "crop",
    title: "Crop image",
    shortTitle: "Crop",
    description:
      "Crop an exact rectangle after applying the image's orientation.",
    category: "geometry",
    endpoint: "/api/v2/images/crop",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      mode: "rectangle",
      left: 0,
      top: 0,
      width: 800,
      height: 800,
      aspectWidth: 1,
      aspectHeight: 1,
      position: "center",
    },
    controls: [
      {
        type: "select",
        path: "mode",
        label: "Crop mode",
        options: [
          { label: "Exact rectangle", value: "rectangle" },
          { label: "Aspect ratio", value: "aspect" },
        ],
      },
      {
        type: "number",
        path: "left",
        label: "Left",
        min: 0,
        max: 20000,
        unit: "px",
        visibleWhen: { path: "mode", equals: "rectangle" },
      },
      {
        type: "number",
        path: "top",
        label: "Top",
        min: 0,
        max: 20000,
        unit: "px",
        visibleWhen: { path: "mode", equals: "rectangle" },
      },
      {
        type: "number",
        path: "width",
        label: "Width",
        min: 1,
        max: 20000,
        unit: "px",
        visibleWhen: { path: "mode", equals: "rectangle" },
      },
      {
        type: "number",
        path: "height",
        label: "Height",
        min: 1,
        max: 20000,
        unit: "px",
        visibleWhen: { path: "mode", equals: "rectangle" },
      },
      {
        type: "number",
        path: "aspectWidth",
        label: "Aspect width",
        min: 0.1,
        max: 1000,
        visibleWhen: { path: "mode", equals: "aspect" },
      },
      {
        type: "number",
        path: "aspectHeight",
        label: "Aspect height",
        min: 0.1,
        max: 1000,
        visibleWhen: { path: "mode", equals: "aspect" },
      },
      {
        type: "select",
        path: "position",
        label: "Position",
        options: positionOptions,
        visibleWhen: { path: "mode", equals: "aspect" },
      },
    ],
    keywords: ["trim region", "rectangle", "aspect ratio", "square"],
  },
  {
    id: "rotate",
    slug: "rotate-flip",
    title: "Rotate or flip",
    shortTitle: "Rotate / flip",
    description:
      "Rotate through any angle and optionally mirror horizontally or vertically.",
    category: "geometry",
    endpoint: "/api/v2/images/rotate",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      angle: 90,
      flipHorizontal: false,
      flipVertical: false,
      background: "#000000",
    },
    controls: [
      {
        type: "range",
        path: "angle",
        label: "Angle",
        min: -360,
        max: 360,
        step: 1,
        unit: "°",
      },
      { type: "boolean", path: "flipHorizontal", label: "Flip horizontally" },
      { type: "boolean", path: "flipVertical", label: "Flip vertically" },
      { type: "color", path: "background", label: "Exposed background" },
    ],
    keywords: ["rotate", "mirror", "orientation", "angle"],
  },
  {
    id: "trim",
    slug: "trim",
    title: "Trim borders",
    shortTitle: "Trim",
    description:
      "Remove edges that match a background color within a controlled tolerance.",
    category: "geometry",
    endpoint: "/api/v2/images/trim",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: { threshold: 10, background: "#ffffff", lineArt: false },
    controls: [
      {
        type: "range",
        path: "threshold",
        label: "Match threshold",
        min: 0,
        max: 100,
        step: 1,
      },
      {
        type: "color",
        path: "background",
        label: "Border color",
        optional: true,
      },
      { type: "boolean", path: "lineArt", label: "Line-art mode" },
    ],
    keywords: ["border", "whitespace", "edges", "threshold"],
  },
  {
    id: "extend",
    slug: "extend-pad",
    title: "Extend or pad canvas",
    shortTitle: "Extend / pad",
    description:
      "Add pixels to any edge using a color, copied pixels, repeat, or mirror behavior.",
    category: "geometry",
    endpoint: "/api/v2/images/extend",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      top: 24,
      right: 24,
      bottom: 24,
      left: 24,
      mode: "background",
      background: "#00000000",
    },
    controls: [
      {
        type: "number",
        path: "top",
        label: "Top",
        min: 0,
        max: 20000,
        unit: "px",
      },
      {
        type: "number",
        path: "right",
        label: "Right",
        min: 0,
        max: 20000,
        unit: "px",
      },
      {
        type: "number",
        path: "bottom",
        label: "Bottom",
        min: 0,
        max: 20000,
        unit: "px",
      },
      {
        type: "number",
        path: "left",
        label: "Left",
        min: 0,
        max: 20000,
        unit: "px",
      },
      {
        type: "select",
        path: "mode",
        label: "Fill behavior",
        options: [
          { label: "Background color", value: "background" },
          { label: "Copy edge pixels", value: "copy" },
          { label: "Repeat image", value: "repeat" },
          { label: "Mirror image", value: "mirror" },
        ],
      },
      {
        type: "color",
        path: "background",
        label: "Background",
        visibleWhen: { path: "mode", equals: "background" },
      },
    ],
    keywords: ["pad", "canvas", "border", "outpaint", "mirror"],
  },
  {
    id: "alpha",
    slug: "background-alpha",
    title: "Background and alpha",
    shortTitle: "Background / alpha",
    description:
      "Flatten transparency, ensure or remove an alpha channel, or extract alpha as an image.",
    category: "geometry",
    endpoint: "/api/v2/images/alpha",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: { action: "flatten", background: "#ffffff", alpha: 1 },
    controls: [
      {
        type: "select",
        path: "action",
        label: "Operation",
        options: [
          { label: "Flatten transparency", value: "flatten" },
          { label: "Ensure alpha", value: "ensure" },
          { label: "Remove alpha", value: "remove" },
          { label: "Extract alpha", value: "extract" },
        ],
      },
      {
        type: "color",
        path: "background",
        label: "Flattening background",
        visibleWhen: { path: "action", equals: "flatten" },
      },
      {
        type: "range",
        path: "alpha",
        label: "Alpha value",
        min: 0,
        max: 1,
        step: 0.05,
        visibleWhen: { path: "action", equals: "ensure" },
      },
    ],
    keywords: ["transparent", "transparency", "background", "alpha mask"],
  },
  {
    id: "adjust",
    slug: "adjust-color",
    title: "Adjust color",
    shortTitle: "Adjust color",
    description:
      "Control brightness, saturation, hue, contrast, and gamma with bounded values.",
    category: "color",
    endpoint: "/api/v2/images/adjust",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: { brightness: 1, saturation: 1, hue: 0, contrast: 0, gamma: 1 },
    controls: [
      {
        type: "range",
        path: "brightness",
        label: "Brightness",
        min: 0.1,
        max: 3,
        step: 0.05,
      },
      {
        type: "range",
        path: "saturation",
        label: "Saturation",
        min: 0,
        max: 3,
        step: 0.05,
      },
      {
        type: "range",
        path: "hue",
        label: "Hue",
        min: -360,
        max: 360,
        step: 1,
        unit: "°",
      },
      {
        type: "range",
        path: "contrast",
        label: "Contrast",
        min: -1,
        max: 1,
        step: 0.05,
      },
      {
        type: "range",
        path: "gamma",
        label: "Gamma",
        min: 1,
        max: 3,
        step: 0.05,
      },
    ],
    keywords: ["brightness", "saturation", "hue", "contrast", "gamma"],
  },
  {
    id: "normalize",
    slug: "normalize-clahe",
    title: "Normalize or apply CLAHE",
    shortTitle: "Normalize / CLAHE",
    description:
      "Stretch global contrast or use local histogram equalization for uneven lighting.",
    category: "color",
    endpoint: "/api/v2/images/normalize",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      mode: "normalize",
      lower: 1,
      upper: 99,
      width: 3,
      height: 3,
      maxSlope: 3,
    },
    controls: [
      {
        type: "select",
        path: "mode",
        label: "Method",
        options: [
          { label: "Normalize", value: "normalize" },
          { label: "CLAHE", value: "clahe" },
        ],
      },
      {
        type: "range",
        path: "lower",
        label: "Lower percentile",
        min: 0,
        max: 99,
        step: 1,
        unit: "%",
        visibleWhen: { path: "mode", equals: "normalize" },
      },
      {
        type: "range",
        path: "upper",
        label: "Upper percentile",
        min: 1,
        max: 100,
        step: 1,
        unit: "%",
        visibleWhen: { path: "mode", equals: "normalize" },
      },
      {
        type: "number",
        path: "width",
        label: "CLAHE grid width",
        min: 1,
        max: 256,
        visibleWhen: { path: "mode", equals: "clahe" },
      },
      {
        type: "number",
        path: "height",
        label: "CLAHE grid height",
        min: 1,
        max: 256,
        visibleWhen: { path: "mode", equals: "clahe" },
      },
      {
        type: "range",
        path: "maxSlope",
        label: "CLAHE max slope",
        min: 0,
        max: 100,
        step: 1,
        visibleWhen: { path: "mode", equals: "clahe" },
      },
    ],
    keywords: ["contrast", "histogram equalization", "clahe", "tone"],
  },
  {
    id: "filter",
    slug: "filters",
    title: "Image filters",
    shortTitle: "Filters",
    description:
      "Apply deterministic grayscale, sepia, invert, threshold, or tint effects.",
    category: "color",
    endpoint: "/api/v2/images/filter",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      kind: "grayscale",
      alpha: false,
      value: 128,
      grayscale: true,
      color: "#6d5dfc",
    },
    controls: [
      {
        type: "select",
        path: "kind",
        label: "Filter",
        options: [
          { label: "Grayscale", value: "grayscale" },
          { label: "Sepia", value: "sepia" },
          { label: "Invert", value: "invert" },
          { label: "Threshold", value: "threshold" },
          { label: "Tint", value: "tint" },
        ],
      },
      {
        type: "boolean",
        path: "alpha",
        label: "Invert alpha",
        visibleWhen: { path: "kind", equals: "invert" },
      },
      {
        type: "range",
        path: "value",
        label: "Threshold",
        min: 0,
        max: 255,
        step: 1,
        visibleWhen: { path: "kind", equals: "threshold" },
      },
      {
        type: "boolean",
        path: "grayscale",
        label: "Grayscale first",
        visibleWhen: { path: "kind", equals: "threshold" },
      },
      {
        type: "color",
        path: "color",
        label: "Tint color",
        visibleWhen: { path: "kind", equals: "tint" },
      },
    ],
    keywords: ["grayscale", "sepia", "invert", "threshold", "tint"],
  },
  {
    id: "blur-sharpen",
    slug: "blur-sharpen-median",
    title: "Blur, sharpen, or median filter",
    shortTitle: "Blur / sharpen / median",
    description:
      "Apply bounded local filtering for softness, edge detail, or speckle reduction.",
    category: "color",
    endpoint: "/api/v2/images/blur-sharpen",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: { kind: "blur", sigma: 2, size: 3 },
    controls: [
      {
        type: "select",
        path: "kind",
        label: "Filter",
        options: [
          { label: "Blur", value: "blur" },
          { label: "Sharpen", value: "sharpen" },
          { label: "Median", value: "median" },
        ],
      },
      {
        type: "range",
        path: "sigma",
        label: "Blur sigma",
        min: 0.3,
        max: 100,
        step: 0.1,
        visibleWhen: { path: "kind", equals: "blur" },
      },
      {
        type: "number",
        path: "sigma",
        label: "Sharpen sigma",
        min: 0.000001,
        max: 10,
        step: 0.1,
        visibleWhen: { path: "kind", equals: "sharpen" },
      },
      {
        type: "number",
        path: "m1",
        label: "Flat-area amount",
        min: 0,
        max: 100,
        step: 0.1,
        optional: true,
        visibleWhen: { path: "kind", equals: "sharpen" },
      },
      {
        type: "number",
        path: "m2",
        label: "Jagged-area amount",
        min: 0,
        max: 100,
        step: 0.1,
        optional: true,
        visibleWhen: { path: "kind", equals: "sharpen" },
      },
      {
        type: "number",
        path: "x1",
        label: "Threshold X1",
        min: 0,
        max: 1000000,
        optional: true,
        visibleWhen: { path: "kind", equals: "sharpen" },
      },
      {
        type: "number",
        path: "y2",
        label: "Threshold Y2",
        min: 0,
        max: 1000000,
        optional: true,
        visibleWhen: { path: "kind", equals: "sharpen" },
      },
      {
        type: "number",
        path: "y3",
        label: "Threshold Y3",
        min: 0,
        max: 1000000,
        optional: true,
        visibleWhen: { path: "kind", equals: "sharpen" },
      },
      {
        type: "number",
        path: "size",
        label: "Median window",
        min: 1,
        max: 25,
        step: 2,
        visibleWhen: { path: "kind", equals: "median" },
      },
    ],
    keywords: ["blur", "sharpen", "median", "noise", "focus"],
  },
  {
    id: "pixelate",
    slug: "pixelate",
    title: "Pixelate image",
    shortTitle: "Pixelate",
    description:
      "Create a deterministic mosaic effect using a chosen block size.",
    category: "color",
    endpoint: "/api/v2/images/pixelate",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: { blockSize: 12 },
    controls: [
      {
        type: "range",
        path: "blockSize",
        label: "Block size",
        min: 2,
        max: 200,
        step: 1,
        unit: "px",
      },
    ],
    keywords: ["mosaic", "pixel", "block", "censor"],
  },
  {
    id: "watermark",
    slug: "watermark",
    title: "Watermark image",
    shortTitle: "Watermark",
    description:
      "Place validated text or image overlays using predictable anchors, scale, opacity, and offsets.",
    category: "composition",
    endpoint: "/api/v2/images/watermark",
    inputKind: "overlay",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      kind: "text",
      text: "Image Everything",
      font: "sans",
      color: "#ffffff",
      opacity: 0.7,
      anchor: "bottom-right",
      scale: 0.25,
      offsetX: 24,
      offsetY: 24,
    },
    controls: [
      {
        type: "select",
        path: "kind",
        label: "Watermark type",
        options: [
          { label: "Text", value: "text" },
          { label: "Image", value: "image" },
        ],
      },
      {
        type: "text",
        path: "text",
        label: "Watermark text",
        maxLength: 200,
        visibleWhen: { path: "kind", equals: "text" },
      },
      {
        type: "select",
        path: "font",
        label: "Safe font",
        visibleWhen: { path: "kind", equals: "text" },
        options: [
          { label: "Sans", value: "sans" },
          { label: "Serif", value: "serif" },
          { label: "Monospace", value: "mono" },
        ],
      },
      {
        type: "color",
        path: "color",
        label: "Text color",
        visibleWhen: { path: "kind", equals: "text" },
      },
      {
        type: "color",
        path: "strokeColor",
        label: "Text stroke",
        visibleWhen: { path: "kind", equals: "text" },
      },
      {
        type: "number",
        path: "fontSize",
        label: "Font size",
        min: 8,
        max: 512,
        unit: "px",
        optional: true,
        visibleWhen: { path: "kind", equals: "text" },
      },
      {
        type: "range",
        path: "opacity",
        label: "Opacity",
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        type: "range",
        path: "scale",
        label: "Overlay scale",
        min: 0.01,
        max: 1,
        step: 0.01,
        visibleWhen: { path: "kind", equals: "image" },
      },
      {
        type: "select",
        path: "anchor",
        label: "Anchor",
        options: anchorOptions,
      },
      {
        type: "number",
        path: "offsetX",
        label: "Horizontal offset",
        min: -20000,
        max: 20000,
        unit: "px",
      },
      {
        type: "number",
        path: "offsetY",
        label: "Vertical offset",
        min: -20000,
        max: 20000,
        unit: "px",
      },
    ],
    inputLabel: "Base image",
    secondaryInputLabel: "Watermark image",
    keywords: ["logo", "brand", "stamp", "overlay", "copyright"],
  },
  {
    id: "frame",
    slug: "frame-rounded-corners",
    title: "Frame and round corners",
    shortTitle: "Frame / rounded corners",
    description:
      "Add a border and rounded corners with an optional background behind transparent corners.",
    category: "composition",
    endpoint: "/api/v2/images/frame",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: {
      border: 24,
      radius: 32,
      color: "#ffffff",
      background: "#000000",
    },
    controls: [
      {
        type: "number",
        path: "border",
        label: "Border",
        min: 0,
        max: 2000,
        unit: "px",
      },
      {
        type: "number",
        path: "radius",
        label: "Corner radius",
        min: 0,
        max: 10000,
        unit: "px",
      },
      { type: "color", path: "color", label: "Frame color" },
      {
        type: "color",
        path: "background",
        label: "Corner background",
        optional: true,
      },
    ],
    keywords: ["border", "radius", "rounded", "frame"],
  },
  {
    id: "collage",
    slug: "collage-contact-sheet",
    title: "Collage and contact sheet",
    shortTitle: "Collage / contact sheet",
    description:
      "Arrange 2–20 images in a grid, horizontal strip, or vertical strip.",
    category: "composition",
    endpoint: "/api/v2/images/collage",
    inputKind: "multi",
    resultKind: "image",
    controlMode: "fields",
    minimumFiles: 2,
    maximumFiles: 20,
    defaults: {
      layout: "grid",
      columns: 3,
      cellWidth: 640,
      cellHeight: 480,
      fit: "contain",
      gap: 16,
      padding: 16,
      background: "#ffffff",
      format: "jpeg",
      quality: 85,
    },
    controls: [
      {
        type: "select",
        path: "layout",
        label: "Layout",
        options: [
          { label: "Grid", value: "grid" },
          { label: "Horizontal", value: "horizontal" },
          { label: "Vertical", value: "vertical" },
        ],
      },
      {
        type: "number",
        path: "columns",
        label: "Columns",
        min: 1,
        max: 20,
        visibleWhen: { path: "layout", equals: "grid" },
      },
      {
        type: "number",
        path: "cellWidth",
        label: "Cell width",
        min: 1,
        max: 20000,
        unit: "px",
      },
      {
        type: "number",
        path: "cellHeight",
        label: "Cell height",
        min: 1,
        max: 20000,
        unit: "px",
      },
      { type: "select", path: "fit", label: "Cell fit", options: fitOptions },
      {
        type: "number",
        path: "gap",
        label: "Gap",
        min: 0,
        max: 1000,
        unit: "px",
      },
      {
        type: "number",
        path: "padding",
        label: "Outer padding",
        min: 0,
        max: 2000,
        unit: "px",
      },
      { type: "color", path: "background", label: "Background" },
      outputFormat,
      {
        ...quality,
        visibleWhen: {
          path: "format",
          oneOf: formatsForEncoderOption("quality"),
        },
      },
    ],
    keywords: ["collage", "contact sheet", "grid", "stitch", "combine"],
  },
  {
    id: "metadata",
    slug: "metadata-inspector",
    title: "Metadata inspector",
    shortTitle: "Metadata inspector",
    description:
      "Read recognized EXIF, IPTC, XMP, GPS, ICC, and core image properties.",
    category: "metadata",
    endpoint: "/api/v2/images/metadata",
    inputKind: "single",
    resultKind: "json",
    controlMode: "fields",
    defaults: { includeRaw: false, includeGps: true },
    controls: [
      { type: "boolean", path: "includeRaw", label: "Include raw tag blocks" },
      { type: "boolean", path: "includeGps", label: "Include GPS metadata" },
    ],
    keywords: ["exif", "iptc", "xmp", "gps", "icc", "camera"],
  },
  {
    id: "metadata-clean",
    slug: "metadata-cleaner",
    title: "Metadata cleaner",
    shortTitle: "Metadata cleaner",
    description:
      "Apply a privacy preset, strip all metadata, or preserve selected safe fields.",
    category: "metadata",
    endpoint: "/api/v2/images/metadata/clean",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: { policy: "privacy", preserve: [] },
    controls: [
      {
        type: "select",
        path: "policy",
        label: "Cleaning policy",
        options: [
          { label: "Privacy", value: "privacy" },
          { label: "Strip everything", value: "strip-all" },
          { label: "Preserve selected", value: "preserve-selected" },
        ],
      },
      {
        type: "choice-list",
        path: "preserve",
        label: "Preserve fields",
        visibleWhen: { path: "policy", equals: "preserve-selected" },
        options: [
          { label: "Orientation", value: "orientation" },
          { label: "ICC color profile", value: "icc" },
          { label: "EXIF", value: "exif" },
          { label: "XMP", value: "xmp" },
        ],
      },
    ],
    keywords: ["remove exif", "privacy", "gps", "strip metadata"],
  },
  {
    id: "metadata-edit",
    slug: "metadata-editor",
    title: "Metadata editor",
    shortTitle: "Metadata editor",
    description:
      "Write a safe whitelist of common authorship, description, date, software, and density fields.",
    category: "metadata",
    endpoint: "/api/v2/images/metadata/edit",
    inputKind: "single",
    resultKind: "image",
    controlMode: "fields",
    defaults: { software: "Image Everything", preserveExisting: false },
    controls: [
      {
        type: "text",
        path: "artist",
        label: "Artist",
        optional: true,
        maxLength: 200,
      },
      {
        type: "text",
        path: "copyright",
        label: "Copyright",
        optional: true,
        maxLength: 300,
      },
      {
        type: "textarea",
        path: "description",
        label: "Description",
        optional: true,
        maxLength: 2000,
      },
      {
        type: "text",
        path: "software",
        label: "Software",
        optional: true,
        maxLength: 200,
      },
      {
        type: "date",
        path: "capturedAt",
        label: "Capture date",
        description:
          "Sent to the API as an ISO 8601 instant with an explicit UTC offset.",
        optional: true,
      },
      {
        type: "number",
        path: "density",
        label: "Density",
        min: 1,
        max: 100000,
        unit: "DPI",
        optional: true,
      },
      {
        type: "boolean",
        path: "preserveExisting",
        label: "Preserve existing metadata",
      },
    ],
    keywords: ["write exif", "artist", "copyright", "description", "density"],
  },
  {
    id: "stats",
    slug: "image-statistics",
    title: "Image statistics",
    shortTitle: "Image statistics",
    description:
      "Measure dimensions, color space, entropy, sharpness, dominant color, and per-channel statistics.",
    category: "metadata",
    endpoint: "/api/v2/images/analyze/stats",
    inputKind: "single",
    resultKind: "json",
    controlMode: "fields",
    defaults: { includeChannels: true },
    controls: [
      {
        type: "boolean",
        path: "includeChannels",
        label: "Include per-channel statistics",
      },
    ],
    keywords: [
      "entropy",
      "sharpness",
      "dominant color",
      "channels",
      "dimensions",
    ],
  },
  {
    id: "palette",
    slug: "palette",
    title: "Extract color palette",
    shortTitle: "Palette",
    description:
      "Sample a deterministic palette and estimate the percentage represented by each color.",
    category: "metadata",
    endpoint: "/api/v2/images/analyze/palette",
    inputKind: "single",
    resultKind: "json",
    controlMode: "fields",
    defaults: { colors: 8, sampleSize: 128 },
    controls: [
      {
        type: "range",
        path: "colors",
        label: "Number of colors",
        min: 2,
        max: 32,
        step: 1,
      },
      {
        type: "number",
        path: "sampleSize",
        label: "Sampling resolution",
        min: 16,
        max: 1024,
        step: 16,
      },
    ],
    keywords: ["colors", "dominant", "swatches", "percentage"],
  },
  {
    id: "histogram",
    slug: "histogram",
    title: "Image histogram",
    shortTitle: "Histogram",
    description:
      "Return RGB, RGBA, or luminance histogram bins as structured data.",
    category: "metadata",
    endpoint: "/api/v2/images/analyze/histogram",
    inputKind: "single",
    resultKind: "json",
    controlMode: "fields",
    defaults: { mode: "rgb", bins: 256 },
    controls: [
      {
        type: "select",
        path: "mode",
        label: "Channels",
        options: [
          { label: "RGB", value: "rgb" },
          { label: "RGBA", value: "rgba" },
          { label: "Luminance", value: "luminance" },
        ],
      },
      {
        type: "select",
        path: "bins",
        label: "Bins",
        options: [
          { label: "16", value: 16 },
          { label: "32", value: 32 },
          { label: "64", value: 64 },
          { label: "128", value: 128 },
          { label: "256", value: 256 },
        ],
      },
    ],
    keywords: ["rgb", "rgba", "luminance", "bins", "tone"],
  },
  {
    id: "compare",
    slug: "compare",
    title: "Compare two images",
    shortTitle: "Compare",
    description:
      "Calculate MAE, RMSE, and differing-pixel percentage, with an optional PNG difference view.",
    category: "metadata",
    endpoint: "/api/v2/images/analyze/compare",
    inputKind: "dual",
    resultKind: "json",
    controlMode: "fields",
    defaults: { resize: "error", threshold: 0, includeAlpha: true, amplify: 4 },
    controls: [
      {
        type: "select",
        path: "resize",
        label: "Dimension mismatch",
        options: [
          { label: "Return an error", value: "error" },
          { label: "Match first image", value: "first" },
          { label: "Use smallest dimensions", value: "smallest" },
          { label: "Use largest dimensions", value: "largest" },
        ],
      },
      {
        type: "range",
        path: "threshold",
        label: "Difference threshold",
        min: 0,
        max: 255,
        step: 1,
      },
      { type: "boolean", path: "includeAlpha", label: "Compare alpha" },
      {
        type: "range",
        path: "amplify",
        label: "Difference amplification",
        min: 1,
        max: 20,
        step: 0.5,
      },
    ],
    inputLabel: "Reference image",
    secondaryInputLabel: "Comparison image",
    auxiliaryResult: {
      endpoint: "/api/v2/images/analyze/compare/diff",
      kind: "image",
      label: "Difference view",
    },
    keywords: ["diff", "difference", "mae", "rmse", "pixel"],
  },
  {
    id: "process",
    slug: "pipeline",
    title: "Image pipeline",
    shortTitle: "Pipeline",
    description:
      "Build, reorder, duplicate, enable, disable, import, and export a validated one-decode pipeline.",
    category: "automation",
    endpoint: "/api/v2/images/process",
    inputKind: "single",
    resultKind: "image",
    controlMode: "pipeline",
    defaults: {
      version: 1,
      steps: [
        {
          id: "step-resize",
          op: "resize",
          enabled: true,
          options: { width: 1600, fit: "inside", withoutEnlargement: true },
        },
      ],
      output: { format: "webp", quality: 82 },
    },
    controls: [],
    keywords: ["workflow", "chain", "preset", "automation", "recipe"],
  },
  {
    id: "batch",
    slug: "batch",
    title: "Batch pipeline",
    shortTitle: "Batch",
    description:
      "Run one reusable pipeline across 1–20 files and download a ZIP with per-file results.",
    category: "automation",
    endpoint: "/api/v2/images/batch",
    inputKind: "multi",
    resultKind: "zip",
    controlMode: "pipeline",
    minimumFiles: 1,
    maximumFiles: 20,
    defaults: {
      pipeline: {
        version: 1,
        steps: [
          {
            id: "step-resize",
            op: "resize",
            enabled: true,
            options: { width: 1600, fit: "inside", withoutEnlargement: true },
          },
        ],
        output: { format: "webp", quality: 82 },
      },
      continueOnError: true,
      filenamePrefix: "processed",
    },
    controls: [],
    keywords: ["bulk", "zip", "many", "workflow", "queue"],
  },
] as const satisfies ToolManifest

export type ToolId = (typeof TOOL_MANIFEST)[number]["id"]
export type ToolSlug = (typeof TOOL_MANIFEST)[number]["slug"]

export const TOOL_ALIASES: Record<string, ToolSlug> = {
  "auto-enhance": "quick-enhance",
  clean: "metadata-cleaner",
  transform: "pipeline",
  metadata: "metadata-inspector",
  rotate: "rotate-flip",
  responsive: "responsive-set",
  frame: "frame-rounded-corners",
  collage: "collage-contact-sheet",
}

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOL_MANIFEST.find((tool) => tool.slug === slug)
}

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOL_MANIFEST.find((tool) => tool.id === id)
}

export function resolveToolSlug(slug: string): ToolSlug | undefined {
  if (getToolBySlug(slug)) return slug as ToolSlug
  const toolById = getToolById(slug)
  if (toolById) return toolById.slug as ToolSlug
  return TOOL_ALIASES[slug]
}

export function cloneToolDefaults(
  tool: Pick<ToolDefinition, "id" | "defaults">
): Record<string, SerializableValue> {
  const parsed = getToolOptionsSchema(tool.id).parse(tool.defaults)
  return JSON.parse(JSON.stringify(parsed)) as Record<string, SerializableValue>
}
