import {
  Activity,
  Aperture,
  BarChart3,
  Blend,
  BoxSelect,
  Braces,
  CircleDot,
  Columns3,
  Contrast,
  Crop,
  Eraser,
  FileArchive,
  FileOutput,
  Focus,
  Frame,
  ImageDown,
  Images,
  Layers,
  Maximize2,
  Palette,
  PanelTop,
  Pipette,
  Replace,
  RotateCw,
  ScanSearch,
  SlidersHorizontal,
  Sparkles,
  Stamp,
  type LucideIcon,
} from "lucide-react"

import type { ToolId } from "./manifest"

export const TOOL_ICON_REGISTRY: Record<ToolId, LucideIcon> = {
  compress: ImageDown,
  "compress-to-size": CircleDot,
  resize: Maximize2,
  convert: Replace,
  responsive: FileArchive,
  "quick-enhance": Sparkles,
  crop: Crop,
  rotate: RotateCw,
  trim: BoxSelect,
  extend: PanelTop,
  alpha: Blend,
  adjust: SlidersHorizontal,
  normalize: Contrast,
  filter: Aperture,
  "blur-sharpen": Focus,
  pixelate: Columns3,
  watermark: Stamp,
  frame: Frame,
  collage: Images,
  metadata: ScanSearch,
  "metadata-clean": Eraser,
  "metadata-edit": Braces,
  stats: Activity,
  palette: Palette,
  histogram: BarChart3,
  compare: Pipette,
  process: Layers,
  batch: FileOutput,
}
