import {
  Activity,
  Aperture,
  BarChart3,
  Blend,
  BoxSelect,
  Braces,
  CircleDot,
  Columns3,
  Contrast,
  Crop,
  Binary,
  Code,
  FileCode,
  Eraser,
  FileArchive,
  FileOutput,
  Focus,
  Frame,
  ImageDown,
  Images,
  Layers,
  Maximize2,
  Palette,
  PanelTop,
  Pipette,
  Replace,
  RotateCw,
  ScanSearch,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Stamp,
  type LucideIcon,
} from "lucide-react"

import type { ToolId } from "./manifest"

export const TOOL_ICON_REGISTRY: Record<ToolId, LucideIcon> = {
  compress: ImageDown,
  "compress-to-size": CircleDot,
  resize: Maximize2,
  convert: Replace,
  responsive: FileArchive,
  "quick-enhance": Sparkles,
  crop: Crop,
  rotate: RotateCw,
  trim: BoxSelect,
  extend: PanelTop,
  alpha: Blend,
  adjust: SlidersHorizontal,
  normalize: Contrast,
  filter: Aperture,
  "blur-sharpen": Focus,
  pixelate: Columns3,
  watermark: Stamp,
  frame: Frame,
  collage: Images,
  metadata: ScanSearch,
  "metadata-clean": Eraser,
  "metadata-edit": Braces,
  stats: Activity,
  palette: Palette,
  histogram: BarChart3,
  compare: Pipette,
  process: Layers,
  batch: FileOutput,
  decode: Binary,
  encode: FileCode,
  "to-base64": Code,
  "from-base64": Braces,
  validate: ShieldCheck,
  "color-space": Palette,
  "extract-channel": Layers,
  duotone: Blend,
  posterize: Columns3,
  solarize: Aperture,
  levels: SlidersHorizontal,
  "color-matrix": Braces,
  convolve: Focus,
  morphology: Contrast,
  "replace-color": Replace,
  "chroma-key": Eraser,
  noise: Sparkles,
  affine: BoxSelect,
  vignette: CircleDot,
  shadow: Layers,
  reflection: Blend,
  tile: Images,
  slice: Crop,
  "sprite-sheet": FileArchive,
  "icon-set": Frame,
  "pixel-inspect": Pipette,
  fingerprint: Binary,
  "auto-orient": RotateCw,
  redact: ShieldCheck,
}
